'use strict';

var tiles = [
  { id: 'r1c1', color: null, value: null, row: 1, column: 1 },
  { id: 'r1c2', color: null, value: null, row: 1, column: 2 },
  { id: 'r1c3', color: null, value: null, row: 1, column: 3 },
  { id: 'r1c4', color: null, value: null, row: 1, column: 4 },
  { id: 'r1c5', color: null, value: null, row: 1, column: 5 },
  { id: 'r2c1', color: null, value: null, row: 2, column: 1 },
  { id: 'r2c2', color: null, value: null, row: 2, column: 2 },
  { id: 'r2c3', color: null, value: null, row: 2, column: 3 },
  { id: 'r2c4', color: null, value: null, row: 2, column: 4 },
  { id: 'r2c5', color: null, value: null, row: 2, column: 5 },
  { id: 'r3c1', color: null, value: null, row: 3, column: 1 },
  { id: 'r3c2', color: null, value: null, row: 3, column: 2 },
  { id: 'r3c3', color: null, value: null, row: 3, column: 3 },
  { id: 'r3c4', color: null, value: null, row: 3, column: 4 },
  { id: 'r3c5', color: null, value: null, row: 3, column: 5 },
  { id: 'r4c1', color: null, value: null, row: 4, column: 1 },
  { id: 'r4c2', color: null, value: null, row: 4, column: 2 },
  { id: 'r4c3', color: null, value: null, row: 4, column: 3 },
  { id: 'r4c4', color: null, value: null, row: 4, column: 4 },
  { id: 'r4c5', color: null, value: null, row: 4, column: 5 },
  { id: 'r5c1', color: null, value: null, row: 5, column: 1 },
  { id: 'r5c2', color: null, value: null, row: 5, column: 2 },
  { id: 'r5c3', color: null, value: null, row: 5, column: 3 },
  { id: 'r5c4', color: null, value: null, row: 5, column: 4 },
  { id: 'r5c5', color: null, value: null, row: 5, column: 5 },
]